### ISSUE TITLE
Pop Up Problem

### ISSUE THREAD

**Issue by gerym77** [t3brightside/microtemplate#1]
dear sirs and madamy, 

i installes your typo3 extension by following your instructions in the documentations.
The basic setup ws fine but when i wanted to ad subpages with popup links following error message shows up at the subpage

> Oops, an error occurred! Code: 2018050916120377194aaf The argument "additionalAttributes" was registered with type "array", but is of type "string" in view helper "TYPO3\CMS\Fluid\ViewHelpers\Link\PageViewHelper". exception code:1256475113 file:/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php line:356 fh_debug trace: file: /typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php" line:247 function:validateArguments file: /typo3fluid/fluid/src/Core/ViewHelper/ViewHelperInvoker.php" line:79 function:initializeArgumentsAndRender file: /typo3fluid/fluid/src/Core/Parser/SyntaxTree/ViewHelperNode.php" line:153 function:invoke file: /typo3fluid/fluid/src/Core/Parser/SyntaxTree/AbstractNode.php" line:58 function:evaluate file: /typo3fluid/fluid/src/Core/Parser/SyntaxTree/AbstractNode.php" line:40 function:evaluateChildNode file: /typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php" line:304 function:evaluateChildNodes file: /typo3fluid/fluid/src/ViewHelpers/ThenViewHelper.php" line:35 function:renderChildren file: " line: function:render 

What can i do about it? many thanks for your help

Gery

i would

**Comment by t3brightside** [comment]
It was a bug with additionalAttributes in: Resources/Private/Partials/CloseLink.html
Fixed now in master.
Thanks for the feedback Gery!
