### ISSUE TITLE
maybe an improvement?

### ISSUE THREAD

**Issue by mikeemike7** [t3brightside/microtemplate#11]
This is one of the greatest Templates for T3. Maybe a suggestion for improvement: Would it be possible to integrate a responsive click-to-call button in the header in future versions, which could be controlled via the constants? Then the template would actually be one of the best out-of-the-box landing pages,too :-)

**Comment by t3brightside** [comment]
@mikeemike7 thanks for the kind words. Not a bad idea, but then again in some cases it's phone nr, sometimes call to action, or link to contact page.

So I think as for now it could be easiest to just add new HTML element on the page and place it over the header with a little bit of custom css.
