### ISSUE TITLE
No horizontal menu?

### ISSUE THREAD

**Issue by Down1972** [t3brightside/microtemplate#12]
Hi!
Isn`t it possible to show a horizontal menubar when i am using a desktop-pc? I liked the old way of navigation very much. Don`t know if it is a bug or a feature to show only the "phone-navigation".

thanks a lot for your work so far

greetings 
Jens

**Comment by t3brightside** [comment]
Yes, horizontal menu as such is removed. As a scroll through page it felt an overkill having it there.
If really needed shouldn't be hard customisation to do...
