### ISSUE TITLE
hmbrgr is not defined

### ISSUE THREAD

**Issue by mikeemike7** [t3brightside/microtemplate#13]
Hi, I have the following problem: On pages of the type "sub" there is a js error message:
"Uncaught ReferenceError: hmbrgr is not defined at merged-123...js?1675599052:102:1" and the code in line 102 (highlighted) is:
**hmbrgr.onclick = function() {**
  hmbrgr.classList.toggle('open');
  menu.classList.toggle('open');
  header.classList.toggle('force-bg');
}
What can be done to fix the error?
Greetings,
mike

...

**Comment by t3brightside** [comment]
Hey, thanks for the feedback. You may want to take a look at the latest dev version. I think it's corrected there.

**Comment by t3brightside** [comment]
Should be ok in latest release.

**Comment by mikeemike7** [comment]
Hi Tanel, now it works fine 👍 (latest version). After updating microtemplate to 4.0.0 and containeritems to 2.1.2, I noticed the following: the images are cropped left and right (text/media elements). If you enter a defined image size for desktop instead, the image is cropped on mobile. I suppose, it has something to do with borders/spaces between rows?

**Comment by t3brightside** [comment]
@mikeemike7 if you have gallerycontent installed it overrides your textmedia element. If you want to use the original textmedia and gallerycontent try installing the latest version 1.7.0 of gallerycontent, it has separate TS template for textmedia so you can leave it out. Anyhow textmedia as such is not fully tested in the template but should act as usual if not overridden.
