### ISSUE TITLE
Text & Media - Media Adjustments

### ISSUE THREAD

**Issue by hanwa11** [t3brightside/microtemplate#14]
Hey Tanel Põld, thanks for your top extension!
Text & Media - Media Adjustments don't work. Values set for width and height have no effect.
Thx. + Greets

**Comment by t3brightside** [comment]
Hey, just tested in latest version in TYPO3 v12. Seems to work more-less as expected. It was never tested for it anyhow. Only thing that didn't seem to function well right now, was placing items right before or after content.

Make sure the gallery extension is not set overriding the default textmeida media part. Anyhow it template has not been tested properly with the functionality. Maybe for the next version...
