### ISSUE TITLE
Error after Creating Gridelements Section on TYPO3 9.5.3

### ISSUE THREAD

**Issue by anderlk** [t3brightside/microtemplate#2]
After creating a Section via Content Wizard the following error message comes up:

> Oops, an error occurred!
> Data structure file /var/www/vhosts/testseite/typo3conf/ext/microtemplate/extensions/gridelements/Configuration/FlexForm/ge-section.xml could not be resolved to an existing file

**Comment by t3brightside** [comment]
Thanks! Should be ok in latest master now. Not tested yet, but looked like a typo in the FlexForm file path upper case vs lower case. Didn't come up in every file system.

**Comment by anderlk** [comment]
Thanks, thats it. Just works fine :)
