### ISSUE TITLE
SVG data image

### ISSUE THREAD

**Issue by eyemd** [t3brightside/microtemplate#3]
There's a problem in some browsers with the (+) / (-) SVGs as backround data-image defined in ge-accordion.css: They don't appear in current FF and Chrome Versions. To fix it I had to convert # into %23.

I got the hint from https://stackoverflow.com/questions/30733607/svg-data-image-not-working-on-firefox-or-chrome-72

**Comment by t3brightside** [comment]
Thanks, indeed, this still has to be overlooked and probably replaced with CSS only solution.

**Comment by t3brightside** [comment]
@eyemd in latest Master there's pure CSS + / - now for accordions, still not IE tested thou.
