### ISSUE TITLE
template, css, js missing

### ISSUE THREAD

**Issue by asche76** [t3brightside/microtemplate#5]
Hi, i'm trying to run the extension with a fresh T3 10 installation, but some things seems not to work.
Static TS is added.
But there is no layout to choose from:
![image](https://user-images.githubusercontent.com/47745128/85201007-393ca580-b2fc-11ea-8c57-16a54a5bb8ae.png)

frontend looks nearly without css, and the all.js has only some lines of code.
![image](https://user-images.githubusercontent.com/47745128/85201048-8d478a00-b2fc-11ea-94cd-21ffb7054c98.png)

Thanks a lot

**Comment by t3brightside** [comment]
Can't confirm it as a bug, more likely looks like a setup issue.
Install instruction doesn't include obvious things like clear cache etc.
Sorry, but we can't provide free support on that level.
