### ISSUE TITLE
Content overflows element

### ISSUE THREAD

**Issue by ulriklpedersen** [t3brightside/microtemplate#6]
Consider changing the following style to prevent content overflowing the section when the screen height is below 590px.

https://github.com/t3brightside/microtemplate/blob/c8dad3edcff4b0bde40ea58ab43a31d473b0b3b7/Resources/Public/Styles/Page/microtemplate.css#L722

The following works for me.

```
@media screen and (max-height: 590px)
.ge-section.fullheight {
    min-height: 100vh;
}
```

**Comment by t3brightside** [comment]
Ah indeed that made sense! Thanks.
