### ISSUE TITLE
Section background image generation is not working in 11.5

### ISSUE THREAD

**Issue by t3brightside** [t3brightside/microtemplate#7]

**Comment by t3brightside** [comment]
Possible core bug, workaround hack applied.

**Comment by ulriklpedersen** [comment]
I'm currently trying to setup version 3.2.1 on TYPO3 11.5.5 and a similar problem occurs to me.

Tried to downgrade to TYPO3 11.5.0 and the problem persists.

The output in the frontend is only a 1x1 pixel background image on the .c-section element. 

EDIT:
As i went through the code I can see the original bug is about a forward slash. That doesn't seem to be the problem anyore.

It looks like the temporary image fails to render.

**Comment by t3brightside** [comment]
You may want to check https://github.com/t3brightside/containeritems/blob/main/Configuration/TypoScript/Section/setup.typoscript
Line: 64
I had to remove '/' from '/fileadmin', that was what caused problems for me. It's not a good solution, but worked in my case.

Anyhow next version of containeritems abandons the use of GIFBUILDER image manipulation and replacing it with CSS filters.

As an alternative you could change the section template to use {f:uri.image(image: '{images.0}'} as background instead of {sectionBgImage}
