### ISSUE TITLE
background images are not rendered + missing } in inline css

### ISSUE THREAD

**Issue by joka123** [t3brightside/microtemplate#8]
hello,
i try to use the microtemplate with typo3 11.5.10 
it seems that rendering the background images are not working. every background image has a 1px x 1px size.

in styles.typoscript in line 140 there is a missing }
					#header {background-color: {$microtemplate.header-bg}

best regards
jk

**Comment by t3brightside** [comment]
BG images system will be completely reworked in next version. gifbuilder won't be used no more...So it's not going to be fixed for now.

**Comment by t3brightside** [comment]
Latest version of containeritems and microtemplate should fix it. No more gifbuilder based background rendering...
