### ISSUE TITLE
Error log

### ISSUE THREAD

**Issue by mikeemike7** [t3brightside/microtemplate#9]
Hi Tanel, first of all thanks for this great template! I noticed some logs with errors (.../typo3temp/var/log/typo3_a0a90dd321.log). 
Is it the template or the installation? The error is:

**Mon, Jun 06 2022 19:47:15 +0200 [WARNING] request="8483a2e3fcc78" component="TYPO3.CMS.Core.TypoScript.Parser.TypoScriptParser": No file or folder found for importing TypoScript on "EXT:microtemplate/ Configuration/PageTS/extensions.typoscript".**

Greetings from Munster

**Comment by t3brightside** [comment]
I think it's a missing file but not cleaned up from the main setup.typoscript file.

**Comment by t3brightside** [comment]
Should be fixed in latest version...
